# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      cargo install --locked trunk
      cargo install wasm-bindgen-cli
      rustup target add wasm32-unknown-unknown
    command: trunk serve

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview
