# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      cargo install trunk --git https://github.com/thedodd/trunk.git
      cargo install wasm-bindgen-cli
      rustup target add wasm32-unknown-unknown
      sudo wget -O /usr/local/bin/minify https://wilsonl.in/minify-html/bin/0.8.0-linux-x86_64
      sudo chmod +x /usr/local/bin/minify
      cargo install minifier
    command: trunk serve