name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cargo install trunk --git https://github.com/thedodd/trunk.git
          cargo install wasm-bindgen-cli
          rustup target add wasm32-unknown-unknown
          sudo wget -O /usr/local/bin/minify https://wilsonl.in/minify-html/bin/0.8.0-linux-x86_64
          sudo chmod +x /usr/local/bin/minify
          cargo install minifier
    - name: Run tests
      run: trunk build --release
