name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cargo install --locked trunk
        cargo install wasm-bindgen-cli
        rustup target add wasm32-unknown-unknown
    - name: Run tests
      run: trunk build --release
